version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: zbx-mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME:-zabbix}
      MYSQL_USER: ${DB_USER:-zabbix}
      MYSQL_PASSWORD: ${DB_PASS:?set in .env}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:?set in .env}
    volumes:
      - zbx-mysql-data:/var/lib/mysql
    networks:
      - zbx-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${DB_ROOT_PASS} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zbx-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${DB_NAME:-zabbix}
      MYSQL_USER: ${DB_USER:-zabbix}
      MYSQL_PASSWORD: ${DB_PASS}
      ZBX_ENABLE_SNMP_TRAPS: "true"
      ZBX_DEBUGLEVEL: ${ZBX_DEBUGLEVEL:-3}
      ZBX_STARTDISCOVERERS: ${ZBX_STARTDISCOVERERS:-3}
      ZBX_STARTPOLLERS: ${ZBX_STARTPOLLERS:-10}
      ZBX_TIMEOUT: ${ZBX_TIMEOUT:-10}
    ports:
      - "10051:10051"
    volumes:
      - ./zbx/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./zbx/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - ./zbx/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./zbx/mibs:/var/lib/zabbix/mibs:rw
    networks:
      - zbx-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zbx-web
    depends_on:
      mysql:
        condition: service_healthy
      zabbix-server:
        condition: service_started
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${DB_NAME:-zabbix}
      MYSQL_USER: ${DB_USER:-zabbix}
      MYSQL_PASSWORD: ${DB_PASS}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME:-Zabbix}
      PHP_TZ: ${PHP_TZ:-Europe/Madrid}
    ports:
      - "${WEB_PORT:-8082}:8080"
      - "${WEB_TLS_PORT:-8445}:8443"
    networks:
      - zbx-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zbx-agent2
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_ACTIVE_CHECKS: "1"
      ZBX_HOSTNAME: ${ZBX_AGENT_HOSTNAME:-docker-host}
    networks:
      - zbx-net
    # privileged: true
    # volumes:
    #   - /:/rootfs:ro
    #   - /var/run/docker.sock:/var/run/docker.sock

networks:
  zbx-net:
    driver: bridge

volumes:
  zbx-mysql-data:
